env:
  browser: true
  es6: true
extends:
  - prettier
  - plugin:prettier/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
parser: babel-eslint
